### ISSUE TITLE
Netflix Stock Profile (DVP)

### ISSUE THREAD

**Issue by asadmehdi785** [SmerlingRosario/dvp-u6-netflix-data#1]
### Criteria 1: Pandas and CSV
* _Score Level:_ 4
* _Comment(s):_ The Jupyter notebook imports the necessary libraries and converts the CSV to a Pandas DataFrame.

### Criteria 2: Implementation of visualizations in spec
* _Score Level:_ 4
* _Comment(s):_ The Jupyter notebook renders all Seaborn visualizations and content provided in the design specification.

### Criteria 3: Color
* _Score Level:_ 3
* _Comment(s):_ Color in visualizations has meaning.

### Criteria 4: Style
* _Score Level:_ 4
* _Comment(s):_ The chart labels and titles are concise and easy to read.

### Criteria 5: Presentation and framing of visualization
* _Score Level:_ 4
* _Comment(s):_ Presentation cohesively presents every chart and has an appropriate description for each.

### Overall Score: 19/20
Outstanding job with this project! You did a great job in all aspects of the project, from setting up the DataFrames, implementing the visualizations, and completing the presentation. The only thing that I wanted to address was the color used in this visualization:

![image](https://user-images.githubusercontent.com/16052289/42730358-20375d90-87c1-11e8-9536-14f5a8ab57fb.png)

It may be better to use different colors for each line, in order to more clearly separate the two graphs. I understand that that's probably a nitpicky issue to address, but since you did an excellent job with the rest of the project I wanted to bring that up.

Great job overall! I hope you enjoyed the course!

**Comment by smerlingcustodio** [comment]
Thank you!
